import { StyleSheet, Text, View } from 'react-native'
import React from 'react'
import { SafeAreaView } from 'react-native-safe-area-context'

const AboutScreen = () => {
  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.textContainer}>
        <Text style={{color:"#FFD700", marginBlock: 10}}>Disclaimer: Generated by chat, Didn't have time to cook</Text>
        <Text style={styles.text}>
          PeekaBoo – Stickers, Memes & Pure Chaos 🎭😂
          Welcome to PeekaBoo, the ultimate app for adding stickers to your photos and making them absolutely ridiculous (or artistic, if that’s your thing). Whether you want to slap a giant crying emoji on your friend’s serious selfie or turn your dog into a space explorer with some stickers – PeekaBoo is here for all your unhinged creativity.

          👨🏾‍💻 Meet the Genius Behind the Madness: Brown
          I’m Brown – a certified sticker enthusiast and meme scientist. I created PeekaBoo because life is too serious, and sometimes, all a photo needs is a well-placed dancing banana. If you ever feel like your pictures are missing something, trust me – it’s probably a sticker.

          🛠 What You Can Do in PeekaBoo:
          ✅ Add Stickers to Any Image – Your face, your pet, your breakfast… no image is safe!
          ✅ Resize, Rotate & Move Stickers – Because the perfect meme requires precision.
          ✅ Layer Stickers Like a Pro – Why stop at one when you can stack them like a digital Picasso?
          ✅ Save & Share with the World – Send your masterpieces to friends, post them online, or just keep them for future blackmail (we don’t judge).

          So go ahead, PeekaBoo the world – and remember: Every photo is better with a sticker (or ten). 🎉🔥
      </Text>
      </View>
    </SafeAreaView>
  )
}

export default AboutScreen

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#171717",
        padding: 20
    },
    textContainer: {
        display: "flex",
        flexDirection: "column",
        gap: 10,
        flex: 1,
    },
    text: {
        color: "#fff",
        fontSize: 15,
        textAlign: "justify",
    }
})